version: '3.1'
services:
  appone:
    container_name: appone
    build:
      context: .
      dockerfile: Dockerfile
    image: appone:latest
    ports:
      - "8081:8081"
    networks:
      - spring-cloud-network
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://0.0.0.0:5432/anu
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  PostgreSQL:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=anu
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  spring-cloud-network:
    driver: bridge